### PR TITLE
lockin dir with survey results

### PR DESCRIPTION
**Pull request by zscole**
created directory for lockin and added survey results

### CODE REVIEW

**Comment by djrtwo** [comment]
Excellent!
Do these have the updates from the followup or is this just the initial answers?

**Comment by zscole** [comment]
These are the initial answers. Haven't had the time to transcribe updated information yet. Will do that asap.

**Comment by djrtwo** [comment]
merging for now so I can link to it from the other doc.
need to get the updated info in there soon though

**Comment by zscole** [comment]
Sure thing. It's on my TODO list for today.

**Pull request merged**
